import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { ShieldCheck, ArrowRight, KeyRound } from 'lucide-react';
import { useAuth } from '../../context/AuthContext';

export default function TwoFactorPage() {
  const [code, setCode] = useState(['8', '4', '2', '9', '1', '0']);
  const [loading, setLoading] = useState(false);
  const { login } = useAuth();
  const navigate = useNavigate();

  const handleVerify = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);
    setTimeout(async () => {
      await login();
      setLoading(false);
      navigate('/dashboard');
    }, 500);
  };

  return (
    <div className="space-y-6 animate-fade-in text-center">
      <div className="w-12 h-12 rounded-2xl bg-cyber-500/15 border border-cyber-500/30 text-cyber-400 flex items-center justify-center mx-auto">
        <ShieldCheck className="w-6 h-6" />
      </div>

      <div className="space-y-1">
        <h2 className="text-xl font-bold text-white">Two-Factor Verification</h2>
        <p className="text-xs text-dark-400">
          Enter the 6-digit security code generated by your Authenticator app
        </p>
      </div>

      <form onSubmit={handleVerify} className="space-y-6">
        <div className="flex justify-center gap-2">
          {code.map((digit, idx) => (
            <input
              key={idx}
              type="text"
              maxLength={1}
              value={digit}
              onChange={(e) => {
                const next = [...code];
                next[idx] = e.target.value;
                setCode(next);
              }}
              className="w-10 h-12 text-center text-lg font-mono font-bold bg-dark-800/80 border border-dark-600 rounded-xl text-white focus:border-cyber-500 focus:outline-none"
            />
          ))}
        </div>

        <button
          type="submit"
          disabled={loading}
          className="btn-primary w-full text-sm py-3 flex items-center justify-center gap-2"
        >
          {loading ? (
            <div className="w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin" />
          ) : (
            <>
              <span>Verify & Access Dashboard</span>
              <ArrowRight className="w-4 h-4" />
            </>
          )}
        </button>
      </form>

      <div className="text-xs text-dark-400 pt-2">
        Having trouble?{' '}
        <button onClick={() => navigate('/login')} className="text-cyber-400 font-semibold hover:underline">
          Use Emergency Backup Codes
        </button>
      </div>
    </div>
  );
}
